modLoader="javafml"
loaderVersion="[4,)"
license="Academic Free License v3.0"

[[mods]]
modId="vanillaplusmachines"
version="0.1"
displayName="VanillaPlusMachines"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Appa, MCreator"
description="This Mod adds some useful Vanilla based Machines"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.vanillaplusmachines]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.vanillaplusmachines]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration